# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

# We're using Visual Studio 2015
image: Visual Studio 2015

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0F41/ccYgoYS098AEpBDGjBToFMvBsrjGLRzOW+ViyY4QrIzVIUmMlKiuNXDDeAs

# Install the pre-requisites for the build.
install:
  # Make sure curl is available
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  # Download the installer for dotnet.
  - mkdir .\scripts
  - curl -SL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1 -o .\scripts\dotnet-install.ps1
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -Version 1.0.0-preview2-003121 -NoPath'
  # Download and unpack docfx
  - mkdir docfx
  - cd docfx
  - curl -SL https://github.com/dotnet/docfx/releases/download/v2.14.1/docfx.zip -o docfx.zip
  - unzip docfx.zip
  - cd ..
  # add dotnet and docfx to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$pwd\docfx;$env:Path"

# Perform the build.
build_script:
  - dotnet --info
  - bash build.sh
  - bash coveralls.sh
  - cd docs
  - bash builddocs.sh

# The tests are run as part of the build.
test: off
