name: Spanner tests against emulator (Spanner changes only)

on:
  pull_request:
    paths:
    - '**[Ss]panner**'
  push:
    branches:
      - main
    paths:
    - '**[Ss]panner**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    # Install .NET 6 for building
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Spanner Emulator
      env:
          SPANNER_EMULATOR_HOST: localhost:9010
          TEST_PROJECT: emulator-test-project
      run: |
        dotnet test -c Release ./apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests --filter SupportedOnEmulator\!=No
        dotnet test -c Release ./apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets
